[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/bio"
  to = "/bio.html"
  status = 200

   [[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200